### ISSUE TITLE
Theme serve command returns scope error

### ISSUE THREAD

**Issue by andershagbard** [Shopify/shopify-cli#1309]
Whenever I run `shopify theme serve`, it returns this error:

```
✗ You are not authorized to edit themes on XXX.myshopify.com.
Make sure you are a user of that store, and allowed to edit themes.
```

`shopify whoami` returns the following:

```
Logged into store XXX.myshopify.com in partner organization XXX Org
```

I can login to this store and edit themes the "normal" way.

## Specifications

- Shopify CLI version: 2.0.1

**Comment by artyrcheek** [comment]
Im having the same issue 🙁

**Comment by graftstudio** [comment]
It appears to be when you create a new development theme via a partner account.

**Comment by spinsch** [comment]
it's the same for me.

somehow the partner account is not correctly linked to a new dev store. i see all stores in my account except the created dev stores after the unite event.

**Comment by macournoyer** [comment]
Hey everyone! Can you confirm you're all using a development store created from the Partner dashboard?

**Comment by iliquifysnacks** [comment]
Same issue for me, also with a development store created from the Partner dashboard.

**Comment by iliquifysnacks** [comment]
I think I know what's happening: Working with dawn you need to be logged in with a staff account, not your partner account. Logging out and then logging in with a staff account with full permissions fixes this specific error.

**Comment by macournoyer** [comment]
Two possible workarounds: You need to have a staff account on the dev shop or, if you’re logging in as the owner, you need to log in directly to the dev shop first through `https://SHOP_DOMAIN.com/admin`.

We're updating the docs w/ this info, and looking at solutions 🙌

**Comment by iliquifysnacks** [comment]
I second that this is a bug. But probably not with the CLI but the dawn theme? I have not yet tried to connect the theme to my Github Account. But for development it is probably not going to be a problem that someone makes edits in the theme editor online that are not synced to git.

**Comment by tommypepsi** [comment]
> You need to have a staff account on the dev shop or, if you’re logging in as the owner, you need to log in directly to the dev shop first through `https://SHOP_DOMAIN.com/admin` (this will create the missing links in the backend).

Is it planned to have it work with only partner account? Creating a staff account is definitely not a possibility for all of our clients so I won't be able to use the shopify CLI for themes until it works with partner account (or maybe an integration with private apps like themekit?)

**Comment by tommypepsi** [comment]
oh ok good to know, I tested it out on a new dev store to test the OS 2.0 so that's probably why! I'll have to test it out on a real store.

**Comment by graftstudio** [comment]
> Two possible workarounds: You need to have a staff account on the dev shop or, if you’re logging in as the owner, you need to log in directly to the dev shop first through `https://SHOP_DOMAIN.com/admin` (this will create the missing links in the backend).
> 
> We're updating the docs w/ this info, and looking at solutions 🙌

Thanks for this. I did try the following:-

- created a new development account via my partner dashboard
- Logged out, then typed in the account url with `/admin` at the end in the browser
- Logged back in
- ended up with the same issue.

So for me, currently i have to create myself a staff account by using a different email address, it seems to be the only way. This then prevents me trying out the Github connect feature since my github account uses my other email address.

Thanks

**Comment by ekwoka** [comment]
I'm having a similar issue where I login but it says I don't have an organization account even though its the login I use to access our organizations partner account to enter the store.

**Comment by seeReadCode** [comment]
I am using a partner dev store created after Unite and it has OS 2.0 enabled.  When I use shopify cli either as the dev store owner OR as a staff member with full account creds, I'm still getting auth errors.  SO I still don't have a flow for developing with Dawn.

**Comment by JayceDugan** [comment]
```
Two possible workarounds: You need to have a staff account on the dev shop or, if you’re logging in as the owner, you need to log in directly to the dev shop first through https://SHOP_DOMAIN.com/admin (this will create the missing links in the backend).

We're updating the docs w/ this info, and looking at solutions 🙌
```

Can confirm logging in directly to the dev shop first this resolved using `shopify theme serve` via expected issues with partner accounts and a new development store.

**Comment by seeReadCode** [comment]
Ok, here's the work around that worked for me.
1. Create partner dev store.
2. Log out of shopify accounts.
3. Login to partner dev store at `/admin` as owner using store specific password and link accounts
4. Login via shopify cli

**Comment by bekahmcdonald** [comment]
Thanks @seeReadCode! That was the only thing that worked for me.

**Comment by Nicolasramos411** [comment]
Step by step how you can solve it:

0) Logout in the partner account that create the store (the store owner)
1) Create a new partner account (for the process to be well understood, we will call it "account 2")
2) Log in with the new account (account 2) in the browser.
3) Go to "Store" and select "Add store". Select the option "managed store", insert the URL of the store you want to develop, and all the permissions.
4) Logout with the account 2.
5) Log in with the first account (the store owner) and go to store you want to develop.
4) Inside the store you will see a pop-up to give colaborator access to the account 2. Give the access.
5) Go to your terminal and use "shopify logout" if you are connected before. Finally use "shopify login --store = STORE" (where "STORE" is the URL of your store) and log in with the account 2.

NOW you can use "shopify theme serve" without problems!.

---------------------------------------------------------------------------------------------------------------------------

Paso a paso como resolver el problema:

0) Cierra sesión en la cuenta partner con la que creaste la tienda (el dueño de la tienda)
1) Crea una nueva cuenta partner (Para que el proceso sea entendible, lo llamaré "cuenta 2")
2) Inicia sesión con la nueva cuenta (cuenta 2) en el navegador.
3) Anda a la sección "Tiendas" y selecciona "Agregar tienda". Selecciona la opción "Tienda gestionada", ingresa el URL de la tienda que quieres desarrollar y todos los permisos.
4) Cierra sesión con la cuenta 2.
5)Anda a tu terminal y usa "shopify logout" si estabas conectado desde antes. Finalmente usa "shopify login --store = STORE" (donde "STORE es la URL de tu tienda) y inicia sesión con la cuenta 2.

AHORA puedes usar "shopify theme serve" sin problemas!

**Comment by kgeiger310** [comment]
Similar to Nicolasramos411, I used a shopify staff account to overcome the permission error on my new DEV store using DAWN.

Exact Steps:

PERMISSION ERROR WORKAROUND
1. Opened DEV store (using Dawn theme) from Partner dashboard
2. Navigated to Settings > Users and Permissions
3. Added a staff account with full permission using different but accessible email address
4. Authenticated with new staff account from email invite
5. Logged out of Partner account & DEV store
6. Logged out of Shopify CLI using > shopify logout
6. Logged into DEV store in browser with new staff credentials
7. Logged into Shopify CLI using > shopify login --store xyz.myshopify.com
8. Page opened in browser indicating authentication was successful, closed page
9. Populated products > shopify populate products 
YAY no error.

**Comment by kgeiger310** [comment]
Hi @Kcharle - Can you log into your DEV store from your partner dashboard?

If yes, log in as owner to new DEV store, and check to make sure the user you created is active - you should see "Congratulations on your growing team! You’ve added a second staff account to your store. Welcome, XYZ! <btn VIEW STAFF >".

You can double check permissions, then make sure your new user has reset their password. You can email them/you instructions from the staff page.

Log out everywhere.

Go to new pw reset instructions and reset pw. Then log into your DEV store - but make sure you log in as new email address (sounds obvious but for me shopify always defaults me to my partner email)

Then go to CLI and try...with fingers crossed.

**Comment by Kcharle** [comment]
Hi @kgeiger310 thanks! Realized I had a bit of confusion on my end, as well as a derp moment where an extension I have to show me a website's IP was covering the store "Settings" link haha. 

I was able to login with the CLI, however I do have a clarification question though.

From what I understand, as a partner within the partner dashboard, you can add other users as owners or staff at a partner level, and that's what I had done. But it looks like I actually need to create a staff member within the specific store itself under Users & Permissions?

Some screenshots of what I'm seeing on my end.

- Logged in as main partner account where the "Development" store was created.
![image](https://user-images.githubusercontent.com/4724339/124686188-a6d45900-dea0-11eb-956b-9b7933797047.png)

- Clicked on the "development" store name in the list of all the stores I have access to within this account and can see both the "owner" and the "staff" user
![image](https://user-images.githubusercontent.com/4724339/124686206-ab007680-dea0-11eb-8c82-d2fa4eb56a4b.png)

- Tried logging in with shopify-cli using "kyle" user email address, received error.

- Checked under "Users & Permissions" for the specific store in question and realized there is no "Staff" added, however I assumed adding a Staff on the partner dashboard would handle this?
![image](https://user-images.githubusercontent.com/4724339/124686608-6f19e100-dea1-11eb-89ea-1e451688b3db.png)

- Verified the "kyle" staff account created under the partner dashboard has full permissions enabled for all stores existing and newly created.
![image](https://user-images.githubusercontent.com/4724339/124687090-42b29480-dea2-11eb-9aab-bc29cd4f5bf6.png)

Am I correct in saying that a staff user has to be added directly to the store, and not on a partner dashboard level for the shopify-cli to work?

**Comment by sebszocinski** [comment]
I don't understand why a collaborator account can't just automatically become a staff user as well (at least for the meantime so we can start using the new features). This seems overly complicated for no reason?

**Comment by kgeiger310** [comment]
@Kcharle Yes, the new user needs to be created in the new store as Staff. And, I agree, this is all just a work-around, essentially, you (and I) should have permission in the CLI as partner/owners, but until they fix the bug, this was the only way I could get it to work....

**Comment by cnscorpions** [comment]
@kgeiger310 thanks, it works.

**Comment by tommypepsi** [comment]
> It should work already for collaborator accounts, if that's what you mean. The only issue should be w/ owners of development stores. Let me know if there's something else that doesn't work for you.

Turns out that's also not working on my side. Collaborator account on one of our client's store. Doing shopify theme serve I get a "You are not authorized to edit themes on". I also just noticed that I get a traceback when I do shopify theme pull:
```
This command ran with ID: 84163
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        36: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/bin/shopify:32:in `<main>'
        35: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        34: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        33: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/bin/shopify:33:in `block in <main>'
        32: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/shopify-cli/core/entry_point.rb:23:in `call'
        31: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/shopify-cli/core/monorail.rb:20:in `log'
        30: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
        29: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/shopify-cli/core/executor.rb:15:in `call'
        28: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        27: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        26: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        25: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        24: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        23: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/shopify-cli/command.rb:19:in `call'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/shopify-cli/sub_command.rb:13:in `call'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/project_types/theme/commands/pull.rb:21:in `call'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/shopify-cli/form.rb:13:in `ask'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/project_types/theme/forms/select.rb:8:in `ask'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:100:in `ask'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:188:in `ask_interactive'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/project_types/theme/forms/select.rb:9:in `block in ask'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/project_types/theme/forms/select.rb:20:in `themes'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/shopify-cli/theme/theme.rb:166:in `all'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/shopify-cli/admin_api.rb:95:in `rest_request'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/shopify-cli/admin_api.rb:92:in `block in rest_request'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/shopify-cli/api.rb:86:in `request'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/shopify-cli-2.0.1/lib/shopify-cli/api.rb:72:in `block in request': 403 (ShopifyCli::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}
```

**Comment by hunterruth** [comment]
@tommypepsi - I'm getting the same error. We developed a landing page using Online Store 1.0 via Themekit, and had plans to develop the full site with 2.0 and Shopify CLI. 

I'm curious if anyone has had any luck revoking access, and re-adding access as a collaborator.

**Comment by tommypepsi** [comment]
@hunterruth Turns out to fix this issue you just have to log out of shopify collaborator account -> run ```shopify login``` -> log to your collaborator account. After that it started working for me. Some people found that out in the slack for shopify partners.

**Comment by hunterruth** [comment]
@tommypepsi oh man, you are a life saver. Thank you so much for responding (and so quickly). That fix worked perfectly for me.

**Comment by evaldas-raisutis** [comment]
I must say I'm surprised the cli has been released in the state that it is. Managed to log into the cli as a partner/organization (had to run gem install wdm, which hasn't been documented), only to find I can't serve or push themes to any of the development stores I've made myself (unauthorized).

![image](https://user-images.githubusercontent.com/3714332/129914235-1f2de97b-3eda-40ff-9ae3-26be08c47ff4.png)

**Comment by nickjohnford** [comment]
This solution by @seeReadCode is the one that has fixed it for me.
 
>     1. Create partner dev store.
> 
>     2. Log out of shopify accounts.
> 
>     3. Login to partner dev store at `/admin` as owner using store specific password and LINK ACCOUNTS
> 
>     4. Login via shopify cli

The important point is that when you've created a new dev store via the partner dashboard it seems you have **not yet linked it fully with your partner account**. Log out of parters, then log **directly** in to the new dev store where it should tell you that you can link it to your partner account (provided that you've used the same partner email for the new store). From then on you can start using it via your partner account with CLI.

**Comment by DurianZ** [comment]
The exact opposite worked for me:
1. logout from store 
2. logout from CLI
3. login to any partner account and then logout again
4. login from CLI

**Comment by rijk** [comment]
Same issue here; I am a partner that is added as a team member (not owner) to a development store. I can login to the store admin via the partner dashboard, but not via [thestore].myshopify.com/admin, I get the following error page:

> **Unable to access [thestore]** 
> It looks like you don't have access to this store. Contact the store administrator for access.

In the CLI I _can_ login to the store, but if I do e.g. `shopify theme serve`, I get a 403 as well:

```
/usr/local/Cellar/shopify-cli/2.12.0/gems/shopify-cli-2.12.0/lib/shopify_cli/api.rb:74:in `block in request': 403 (ShopifyCLI::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}
```

**Comment by arunmecom** [comment]
I was facing the same issue 
What I did
1: Log in to `/admin` and clear cookies 
2: re-enter my login and password for the store 
3: tried `shopify login --store=[store]`  and  `shopify theme serve`
4: and it worked 

We have only one solution using `/admin` but still, people facing issues because of cookies, please try after removing cookies from the admin browser

**Comment by pepicrft** [comment]
👋🏼 
For people running into this issue in the future, we are aware of this workflow not being ideal and we'll prioritize making the necessary changes server-side so that people don't run into this scenario.
Until we implement that, we [are improving the errors ](https://github.com/Shopify/shopify-cli/pull/2299) to make them more actionable. A summary of can be found out in the [caution box](https://shopify.dev/themes/tools/cli/core-commands#loginhttps://shopify.dev/themes/tools/cli/core-commands#login) in this section of the documentation.

**Comment by azure-architect** [comment]
Amazing that the cli was released in this state.

**Comment by evankford** [comment]
Hey, is there any update on why this continues to be the policy: **You can't use Shopify CLI with development stores if you only have Partner staff member access. If you want to use Shopify CLI to work on a development store, then you should be the store owner or create a staff account on the store.**

I believe it's pretty common for Agencies to create partner accounts, and then freelance developers (like me), to be given staff access to that partner account. As it is now my staff partner account cannot use the CLI, even though it has full theme editing permissions outside the CLI. The workaround of creating a separate staff account *works*, but is unacceptable as it takes up staff seats. So I basically can't use the CLI on a large amount of my work. 

Just want some clarification of if this is a bug that you intend to fix or an intentional limitation on staff partner accounts!

**Comment by andershagbard** [comment]
> This issue seems inactive. If it's still relevant, please add a comment saying so. Otherwise, take no action.
> 
> → If there's no activity within a week, then a bot will automatically close this.
> 
> Thanks for helping to improve Shopify's dev tooling and experience.

_Stay alive_

**Comment by hunterruth** [comment]
@andershagbard I'm pretty sure this is resolved. I was recently able to use shopify cli without creating a staff account on a development store. In fact, it wouldn't let me create a staff that matched the partner account. I'm on Version 2.28.0.

**Comment by Cam** [comment]
@hunterruth Unfortunately this issue still rears its ugly head from time to time. Just less often.

**Comment by ajpintos** [comment]
Is not inactive, still happen

**Comment by ajpintos** [comment]
in summary... in 2023... what is the right solution?
