### ISSUE TITLE
`shopify login` will not authenticate correctly

### ISSUE THREAD

**Issue by MatheusMK3** [Shopify/shopify-cli#1962]
# Issue summary

I'm part of a Shopify Partner organization that manages a few Shopify stores, when getting the CLI set-up I had the same issues in two of my machines, both running the gem version 2.9.0, one Ubuntu Linux and other Windows 10.

The issue doesn't let me login on my Partner account neither run functions such as `shopify theme pull` or `shopify theme serve`, saying I'm not authenticated or don't have permissions. In some cases it just straight goes into an error asking to report it to Shopify.

## Expected behavior

Successful login and `shopify theme serve` command working as expected.

## Actual behavior

When running the login command, my browser opens normally where I select the account and it will redirect to `127.0.0.1:3456` with a message telling authentication was successful. The CLI will take a few seconds to respond and then gives the following messages:

<details>
It doesn't appear that you're logged in. You must log into a partner organization or a store staff account.

If trying to log into a store staff account, please use shopify login --store=STORE to log in.
</details>

It does seems to succeed if I login with the store option, but running any commands trigger an error, for example, I get the following by running `shopify theme pull`:

<details>
✗ An unexpected error occured.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

? Send an anonymized error report to Shopify? (Choose with ↑ ↓ ⏎, filter with 'f')
> 1. Yes, send
  2. No, don't send
</details>

While running `shopify theme serve` triggers the following error, even though I do have access to the store:
<details>
┏━━ Error 
┃ You are not authorized to edit themes on shopnamehere.myshopify.com.
┃ Make sure you are a user of that store, and allowed to edit themes.
┃ 
┗━━
</details>

## Steps to reproduce the problem

1. Install the CLI via `gem install shopify-cli` or .deb package
2. Try to login with `shopify login`
3. If failed, try logging in with the store option
4. Try running `shopify theme pull` or `shopify theme serve`

## Specifications

- App type: Shopify CLI
- Operating System: Ubuntu Linux / Windows 10
- Shell: ZSH (Ubuntu) / PowerShell (Windows)
- Ruby version (ruby -v): 2.7.4

**Comment by matt-cos** [comment]
I'm having the same issue. Only difference is I installed the CLI w/ Homebrew

**Comment by abdullah-shah-5** [comment]
make sure you have the staff member access on your store from which you are trying to pull

**Comment by jvlvl-z** [comment]
Incredible that this issue still exists after countless updates... It's been like this for months now.

**Comment by MatheusMK3** [comment]
@abdullah-shah-5 I'm able to access and manage the store normally via the web interface, can change themes, customize, etc, just the CLI doesn't let me

**Comment by wshen001** [comment]
This issue seems got resolved with v2.10.0. @MatheusMK3

**Comment by MatheusMK3** [comment]
Hey @wshen001 thanks for your response! Yes, indeed the crashes gone away, which is cool!

Regarding the login/theme errors, I was still getting a 403 error from the API when trying to pull a theme from one of the stores I could access via the Partner, it got sorted by adding my Shopify account directly as a staff on the shop Zi was trying to work on. Not very intuitive, since I could do everything on the web UI, but works good enough on the mean time.

**Comment by moretime-dev** [comment]
I am having the same issue right now. I will try to add myself as a staff member, as I read here

**Comment by MatheusMK3** [comment]
@moretime-dev seems like the latest versions of the CLI now have proper error messages that indicate that, but seems like for any development stores just having Shopify Partners permission is not enough, you also need to be staff on that store to be able to use the CLI. Also, make sure you login first to the store via the web admin and then run `shopify switch --store=your-store-here.myshopify.com` to set the CLI to the desired store :)
