### ISSUE TITLE
"undefined method `shop' for nil:NilClass (NoMethodError)" or 403 error when running shopify theme serve/pull etc

### ISSUE THREAD

**Issue by ReplicantDeckard** [Shopify/shopify-cli#2093]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

shopify theme serve should start development serve, pull should download theme git, etc

### Actual behavior

"✗ An unexpected error occured.", 404 Forbidden error and/or "undefined method `shop' for nil:NilClass (NoMethodError" in stacktrace

### Stack trace

```shell
/home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/theme/dev_server.rb:83:in `rescue in start': undefined method `shop' for nil:NilClass (NoMethodError)
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/theme/dev_server.rb:29:in `start'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/project_types/theme/commands/serve.rb:25:in `call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/command.rb:27:in `call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/executor.rb:15:in `call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/monorail.rb:30:in `log'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/bin/shopify:49:in `block in <top (required)>'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/bin/shopify:60:in `<top (required)>'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/bin/shopify:23:in `load'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/bin/shopify:23:in `<main>'
/home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/api.rb:74:in `block in request': 403 (ShopifyCLI::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/api.rb:89:in `request'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/admin_api.rb:95:in `rest_request'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/theme/theme.rb:104:in `create'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/theme/development_theme.rb:37:in `ensure_exists!'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/theme/development_theme.rb:74:in `find_or_create!'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/theme/dev_server.rb:31:in `start'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/project_types/theme/commands/serve.rb:25:in `call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/command.rb:27:in `call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/executor.rb:15:in `call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/monorail.rb:30:in `log'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/bin/shopify:49:in `block in <top (required)>'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/bin/shopify:60:in `<top (required)>'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/bin/shopify:23:in `load'
        from /home/hansolo/.rvm/gems/ruby-3.0.0/bin/shopify:23:in `<main>'
```

### Reproduction steps

1. Following steps from scratch at https://shopify.dev/themes/getting-started/create
2. "shopify theme init" -- SUCCESSFUL
3. "shopify login --store [..]" -- SUCCESSFUL
4. "shopify theme serve/pull/push" reports error and fails

The above stacktrace is for "shopify theme serve". For "shopify theme pull" the first line is:

"/home/hansolo/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.12.0/lib/shopify_cli/api.rb:74:in `block in request': 403 (ShopifyCLI::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}"

For Environment Details I'm listing my WSL2 Debian 11 box, but I also downloaded shopify-cli on my Windows 10 box and ran it in Git Bash with the exact same problems. At first I thought I hadn't set up my dev store properly but after a chat with Shopify customer support I was advised to open an issue here.

This is my first Shopify Partner account development store. I created the store and logged in with my browser at admin, then followed the steps in https://shopify.dev/themes/getting-started/create. I'm aware that there are other issues with people getting 403 errors but as far as I can tell they are slightly different than mine.

### Operating System

Debian 11 (on WSL2)

### CLI version (run `shopify version` if you're not sure)

2.12.0

### Shell

bash

### Ruby version (run `ruby -v` if you're not sure)

3.0.0p0

**Comment by ReplicantDeckard** [comment]
This issue was resolved by updating to shopify-cli-2.13.0

**Comment by BryanCastro** [comment]
> This issue was resolved by updating to shopify-cli-2.13.0

Still an issue on 2.15.1

**Comment by joshuarussell10** [comment]
Still an issue following the create a theme guide.

Shopify CLI - 2.15.2

OSX Catalina - 10.15.7
Ruby - 3.0

**Comment by lucidpolygon** [comment]
Same issue
Shopify CLI 2.15.2
ruby 3.1.1
macOS Monterey 12.3
