### ISSUE TITLE
shopify serve failed started. ngrok tunnel has timed out, restarting ... ngrok tunnel could not be stopped. Try running killall -9 ngrok

### ISSUE THREAD

**Issue by gokaka** [Shopify/shopify-cli#952]
@FDiskas

## Same issue here:
```
❯ shopify serve
✗ ngrok tunnel has timed out, restarting ...
✗ ngrok tunnel could not be stopped. Try running killall -9 ngrok

❯ killall -9 ngrok
No matching processes belonging to you were found

❯ shopify serve
✗ ngrok tunnel has timed out, restarting ...
✗ ngrok tunnel could not be stopped. Try running killall -9 ngrok

>_<
```

The problem seems like shopify-cli failed find the PID file in `~/.cache/shopify/sv/ngrok.pid`, and there's also no ngrok is running in background, then it failed to stop the ngrok

## My temporary solution:

- found my Shopify CLI (v1.0.4) was installed in path `/usr/local/Cellar/shopify-cli/1.0.4/`

in your case, the path should be like `/usr/local/Cellar/shopify-cli/1.2.0/`

- comment out the `ShopifyCli::ProcessSupervision.stop(:ngrok)` process in file
`/usr/local/Cellar/shopify-cli/1.0.4/src/lib/shopify-cli/tunnel.rb`
 (https://github.com/Shopify/shopify-app-cli/blob/master/lib/shopify-cli/tunnel.rb#L169-L171)

```
    def restart_ngrok(ctx, port)
#      unless ShopifyCli::ProcessSupervision.stop(:ngrok)
#        ctx.abort(ctx.message('core.tunnel.error.stop'))
#      end
      start_ngrok(ctx, port)
    end
```

- Then rerun `shopify serve`, now it will skip the stop ngrok, everything look good.

```
❯ shopify serve
✗ ngrok tunnel has timed out, restarting ...
✓ ngrok tunnel running at https://6016cf0f5ea2.ngrok.io
...
```

- _**You'd better reverse the `tunnel.rb` changes at last.**_

_Originally posted by @gokaka in https://github.com/Shopify/shopify-app-cli/issues/888#issuecomment-720018790_

**Comment by paulomarg** [comment]
Hi @gokaka, it seems you're using a slightly outdated version of the CLI, and we've recently made changes to ngrok handling - could you please update to the latest version to see if that fixes your issues?

Also, in the future, please avoid mentioning specific team members in new issues - I realize in this case you were just porting the comment over, so I'm just leaving this as a reminder. Our team will investigate all opened issues, and mentioning a member won't change the priority of the issue or necessarily mean that member will handle the issue.

**Comment by kato-takaomi-ams** [comment]
same issue reproduced on windows.

```
> shopify version
1.4.1
```
### My temporary solution:
1. remove files ngrok.log/ngrok.pid.
> C:\Users\[user]\AppData\Local\shopify\sv\ngrok.log
> C:\Users\[user]\AppData\Local\shopify\sv\ngrok.pid
2. retry.
```
> shopify serve
```

**Comment by paulomarg** [comment]
Hey @kato-takaomi-ams, thank you for this! Your solution is actually the right one - the CLI user has to be able to delete / write those files, otherwise it can't start up the tunnel.

This kind of issue can happen if you run the CLI as admin, and then try to run it with a different user, if the second user doesn't have permissions to those files.

**Comment by cbodtorf** [comment]
```
❯ shopify version
1.5.0
```

I believe my issue is related I can't seem to get `shopify serve` to work:
```
❯ shopify serve
✗ ngrok tunnel could not be stopped. Try running killall -9 ngrok
❯ killall -9 ngrok
No matching processes belonging to you were found
```

### What I've Tried:
- originally on previous version `1.4.1`, so I upgraded. Same issue.
- uninstalled and reinstalled. Same issue.
- tried @gokaka temp solution. Same issue.
- deleted ngrok.log and ngrok.pid files. Same issue.

---

my `ngrok.log` file reads:
```
t=2020-12-30T17:12:36-0500 lvl=info msg="no configuration paths supplied"
t=2020-12-30T17:12:36-0500 lvl=info msg="using configuration at default config path" path=/Users/user/.ngrok2/ngrok.yml
t=2020-12-30T17:12:36-0500 lvl=info msg="open config file" path=/Users/user/.ngrok2/ngrok.yml err=nil

ERROR:  You can't enable the console UI and log to stdout or stderr
```

My ngrok.yml is indeed at the default config path.
Also my ngrok works fine if I used it outside of the shopify-app-cli.

**Comment by cbodtorf** [comment]
I figured it out, turns out my `ngrok.yml` had the option `console_ui: true` set. Once I set that to false it works fine.

**Comment by iiewad** [comment]
+1

**Comment by purushothamanr** [comment]
Hi All, 

I am facing an issue,

shopify node serve       
✗ ngrok tunnel could not be stopped. Try running killall -9 ngrok


shopify version         
2.5.0

Can you please help?

**Comment by jpaylor** [comment]
Everything I tried including the suggestions above unfortunately didn't work.

Managed to get past the error by renaming the file `~/.cache/shopify/sv/ngrok.pid` to something else and then ran `shopify node serve` again which caused a new ngrok.pid file to be created.

**Comment by Metturan** [comment]
I'm also having the same issue. Tried to delete ngrok and the ngrok.pid, ngrok.log files and reinstall. But still same message.

**Comment by newtdogg** [comment]
Yeah I'm experiencing this and can't find a solution on here, possibly broken in the current release? Haven't tried an older version...

**Comment by echizenyayota** [comment]
There was not ".ngrok2/ngrok.yml" for some reason after the terminal screen showed "ngrok tunnel could not be stopped. Try running killall -9 ngrok". 

So I made the folder and the file and added the Authtoken in the file again. 

```
$ mkdir ~/.ngrok2
$ touch ~/.ngrok2/ngrok.yml
$ vi ~/.ngrok2/ngrok.yml
authtoken: YOURTOKEN
```

You will find out YOURTOKEN in the "Configuration File" if you access "[https://dashboard.ngrok.com/get-started/your-authtoken](https://dashboard.ngrok.com/get-started/your-authtoken)".

Now, my "shopify node serve" and "ngrok http 8081" are working.

**Comment by PranayKakati26** [comment]
> I figured it out, turns out my `ngrok.yml` had the option `console_ui: true` set. Once I set that to false it works fine.

Where did you find ngrok.yml file?

**Comment by yazumoto** [comment]
Same here....

```
shopify version
2.7.0
```

```
shopify app create node
# App Name test
cd test
shopify app serve
✗ ngrok tunnel has timed out, restarting…
✗ ngrok tunnel could not be stopped. Try running killall -9 ngrok
```

I thought it's my M1 mac problem or something but intel also same.

**Comment by yazumoto** [comment]
I found a solution.
You need to setup ngrok auth token.

### Setup
```
# login to ngrok. https://dashboard.ngrok.com/login
# Get AuthToken
shopify app tunnel auth <token>
Authtoken saved to configuration file: /Users/<username>/.ngrok2/ngrok.yml
```

```
shopify app serve
✓ ngrok tunnel running at https://<something>.ngrok.io, with account seteen
✓ .env saved to project root
? Do you want to update your application url? (Choose with ↑ ↓ ⏎)
> 1. yes
  2. no
```

**Comment by shaibruhis** [comment]
I tried adding my auth token to the yaml file:
```
$ cat ~/.ngrok2/ngrok.yml
authtoken: <my_auth_token>
```

But I'm still experiencing the same issue :/.

```
$ shopify app serve                                                                              
✓ curl @ /usr/bin/curl
✓ tar @ /usr/bin/tar
✓ Installing ngrok…
✗ ngrok tunnel could not be stopped. Try running killall -9 ngrok
```

**Comment by Bytesu** [comment]
`~/.cache/shopify/ngrok authtoken ngroktoken`


this line worked for me

**Comment by gonzaloriestra** [comment]
Thanks for reporting, and sorry for the inconvenience!

This issue has been fixed in the latest release (2.7.1). More details in [this PR](https://github.com/Shopify/shopify-cli/pull/1758).

**Comment by gonzaloriestra** [comment]
Hi @shaibruhis! I don't think that using a M1 Mac affects here. Could you try this?

```
rm ~/.cache/shopify/sv/ngrok.pid
```

**Comment by shaibruhis** [comment]
Hey @gonzaloriestra! I've tried that as well and still no luck:
```
$ rm ~/.cache/shopify/sv/ngrok.pid
$ shopify app serve                          
✗ ngrok tunnel could not be stopped. Try running killall -9 ngrok 
```

**Comment by shaibruhis** [comment]
I think the issue is the ngrok version that shopify is installing. If I do the following, it works.
```
brew install ngrok
cd ~/.cache/shopify/ngrok
ln -s /opt/homebrew/bin/ngrok ~/.cache/shopify/ngrok
```

**Comment by gonzaloriestra** [comment]
@shaibruhis I'm not able to reproduce it, but now I realize that it might indeed be related to the M1. Could you try replacing `~/.cache/shopify/ngrok` with the content from [this zip](https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-arm64.zip)?

**Comment by sapeol** [comment]
Just needed to open the 8081 port in the firewall

**Comment by curtisburns** [comment]
@shaibruhis I had the same problem, also using an M1, your solution worked for me though  👍

```
brew install ngrok/ngrok/ngrok
cd ~/.cache/shopify
rm -rf ngrok
ln -s /opt/homebrew/bin/ngrok ~/.cache/shopify/ngrok
```
Then run `shopify app serve` in your app directory.

Make sure the ngrok auth token is also correctly set in `~/.ngrok2/ngrok.yml` as per the [docs](https://dashboard.ngrok.com/get-started/your-authtoken).

**Comment by curtisburns** [comment]
@gonzaloriestra I'm using 2.10.2

**Comment by sonphan0910** [comment]
> same issue reproduced on windows.
> 
> ```
> > shopify version
> 1.4.1
> ```
> 
> ### My temporary solution:
> 1. remove files ngrok.log/ngrok.pid.
> 
> > C:\Users\[user]\AppData\Local\shopify\sv\ngrok.log
> > C:\Users\[user]\AppData\Local\shopify\sv\ngrok.pid
> 
> 2. retry.
> 
> ```
> > shopify serve
> ```

Thank u so muchhhh.

You really save my life 🙏🙏🙏
